
#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_1_7 --double True 



#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_dqn_1_4 --pav True  --discount_factor 0.1 

#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_dqn_1_2 --pav True --discount_factor 0.15

#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_dqn_1_t --pav True --discount_factor 0.05


#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_dqn_1_6 --pav True  --discount_factor 0.1 

#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_1_1 
#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_1_2
#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_1_3


# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.0 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_0_1_1 --double True
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.0 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_0_1_2 --double True
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.0 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_0_1_3 --double True




# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.27 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_0.2_1_1 --double True
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.27 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_0.2_1_2 --double True
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.27 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_0.2_1_3 --double True




# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.0 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_0_1_1 --averaged_dqn True --num_target_net 4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.0 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_0_1_2 --averaged_dqn True --num_target_net 4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.0 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_0_1_3 --averaged_dqn True --num_target_net 4

# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.13 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_0.1_1_1 --averaged_dqn True --num_target_net 4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.13 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_0.1_1_2 --averaged_dqn True --num_target_net 4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.13 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_0.1_1_3 --averaged_dqn True --num_target_net 4

# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.22 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_0.2_1_1 --averaged_dqn True --num_target_net 4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.22 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_0.2_1_2 --averaged_dqn True --num_target_net 4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.22 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_0.2_1_3 --averaged_dqn True --num_target_net 4




python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.04 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_3_1_1  --averaged_dqn True --num_target_net 3
python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.04 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_3_1_2  --averaged_dqn True --num_target_net 3
python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.04 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/avgdqn_3_1_3  --averaged_dqn True --num_target_net 3

# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.12 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dpavavgdqn_0.1_1_1  --pav True --discount_factor 0.4 --averaged_dqn True --num_target_net 4  
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.12 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dpavavgdqn_0.1_1_2  --pav True --discount_factor 0.4 --averaged_dqn True --num_target_net 4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.12 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dpavavgdqn_0.1_1_3  --pav True --discount_factor 0.4 --averaged_dqn True --num_target_net 4

# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.22 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dpavavgdqn_0.2_1_1  --pav True --discount_factor 0.4 --averaged_dqn True --num_target_net 4 
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.22 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dpavavgdqn_0.2_1_2  --pav True --discount_factor 0.4 --averaged_dqn True --num_target_net 4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.22 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dpavavgdqn_0.2_1_3  --pav True --discount_factor 0.4 --averaged_dqn True --num_target_net 4









# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_0.1_1_1  --pav True  --discount_factor 0.4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_0.1_1_2  --pav True  --discount_factor 0.4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_0.1_1_3  --pav True  --discount_factor 0.4

# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_0.1_1_1 --double True
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_0.1_1_2 --double True
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_0.1_1_3 --double True


# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_0.1_1_1  
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 0 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.21 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --duel False --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_0.2_1_1      --pav True  --discount_factor 0.4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.21 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --duel False --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_0.2_1_2      --pav True  --discount_factor 0.4
# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.21 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --duel False --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_0.2_1_3      --pav True  --discount_factor 0.4




# python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_0.1_1_  






#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_0.1_1_1
#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_0.1_1_2
#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.10 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_0.1_1_3

#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.20 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_0.2_1_1
#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.20 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_0.2_1_2
#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_mode 1 --slot_err_prob 0.20 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/dqn_0.2_1_3


#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/ddqn_1_8    --double True 
#python2 run.py --agt 9 --usr 1 --max_turn 40 --movie_kb_path ./deep_dialog/data/movie_kb.1k.p --dqn_hidden_size 80 --experience_replay_pool_size 10000 --episodes 500 --simulation_epoch_size 1 --run_mode 3 --act_level 0 --slot_err_prob 0.00 --intent_err_prob 0.00 --batch_size 16 --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p --warm_start 1 --warm_start_epochs 50 --planning_steps 0 --boosted 1 --train_world_model 0 --model_type DQN --write_model_dir ./deep_dialog/checkpoints/pav_dqn_1_12 --pav True  --discount_factor 0.1 
